### ISSUE TITLE
Question about receptor annotation

### ISSUE THREAD

**Issue by JanLeipzig** [ventolab/CellphoneDB#27]
Hi,

I'm currently analyzing my CellphoneDB output and would like to verify that I understood the receptor annotation correctly.
There are 'interacting_pair' in the format GeneA_GeneB and cluster pairs in the format X|Y and Y|X.
In addition there is the annotation of 'receptor_a','receptor_b' which can be (True,False), (False,True), (False,False), (True,True).
- (True,False) would mean GeneA_GeneB is a Receptor-Ligand (R-L) pair
- (False,True) would mean GeneA_GeneB is a Ligand-Receptor (L-R) pair
- (False,False) would mean there is no annotation and we don't know
- (True,True) would mean both are receptors and that is weird

Question 1)
Is my understanding correct, that a (True,False) pair is R-L while a (False,True) pair is  L-R?
If yes, is there a reason you did not annotate all interactions in the same way, e.g. always either GeneA OR GeneB being the receptor (if the annotation is available)? Wouldn't that make it much easier to interpret the results?

Question 2)
There are 1396 interactions in 'interaction_input.csv' but only 1029 in my file 'pvalues.txt'. Why are not all interactions part of my pvalues.txt file?
Some interactions are non-significant in each of my cluster pairs so these are not excluded. Do you exclude interactions where the genes are not expressed at all?

Question 3)
Is there a (bio)logical explanation for interactions where both partners are annotated as receptors? 
One example would be 'CPI-SS032E9A219 CX3CR1_CX3CL1'. In this case it seems like a misannotation to me since CX3CL1 is a ligand and not a receptor (but I'm not an interaction expert).
(I used the database release v2.0.0 for my analysis. I have not build v3 yet, but as far as I could see in the other issue the receptor annotation did not change since there is no new protein input file.)

Thank you very much for your support.

**Comment by luzgaral** [comment]
Dear [JanLeipzig](https://github.com/JanLeipzig),

Thank you for using cellphoneDb and sharing your thoughts.

Here our answers:

Question 1. You are correct. Why are we not ordering L/R? Because cellphoneDB has a significant number of interactions that are not directional (eg. extracellular matrix proteins such integrins and collagens rendering (False,False)).

Question 2. Because some interactions may not be present/measured in your dataset. 

Question 3. Thank you for pointing this example, we will review the supporting information. Receptor-receptor interactions are possible and have a biological role. It is not rare between G protein-coupled receptors (GPCRs) but it has been observe din other families as well. 

Let us know if you have any further question,

Best

Luz
