### ISSUE TITLE
How was CellPhoneDB coined?

### ISSUE THREAD

**Issue by biotech25** [ventolab/CellphoneDB#33]
Hi, 

I have a trivial question. I am curious how CellPhoneDB was coined.  I tried to find whether it is acronym or not, but I can't find in the paper.  CellPhoneDB doesn't stand for any long name..?  It is coined to mean 'cell-cell communication' database..? 

Thank you, 
Sanghoon

**Comment by prete** [comment]
[not an official answer] 

> It is coined to mean 'cell-cell communication' database..?

I'm pretty sure that's it. CellPhoneDB helps explore systematic analysis of **cell–cell communication**. So, **Cell Phone** because of cells of course, but also mobile _communication_ devices that use networks that resemble biological cells (aka cellphones). The repository relies on the use of public resources and manual curation and integrates all the information in SQLite relational database (**DB**). Thus, **CellPhoneDB**.

**Comment by sanghoonleepitt** [comment]
Thank you for your explanation, Prete!

Sanghoon
