### ISSUE TITLE
R error when plotting

### ISSUE THREAD

**Issue by RuoyangShao** [ventolab/CellphoneDB#48]
I've just started CellphoneDB by using the statistical analysis mode and everything worked fine until the plotting step.

I ran `cellphonedb plot heatmap_plot` and `cellphonedb plot dotplot` as per the tutorial but both functions gave out the same error message:

> R[write to console]: Loading required package: SeuratObject
> 
> R[write to console]: Attaching sp
> 
> R[write to console]: Error in if (!header) rlabp <- FALSE : argument is of length zero
> 
> [ ][APP][XX/XX/XX-XX:XX:XX][ERROR] R Runtime Exception: Error in if (!header) rlabp <- FALSE : argument is of length zero

It seems like an R issue but I am sure about my R is installed properly. Would you kindly give any hint on what's going wrong? Thx!

**Comment by prete** [comment]
Hi @RuoyangShao  `Loading required package: SeuratObject` is unusual, because CellPhoneDB does not need Seurat at all. The only dependency is ggplot2 . Assuming there's no error in your environment (you should double check). Perhaps you've used a custom output folder or moved the output files somwhere else? In that case try to be explicit about the paths, for example:
- for dot_plot
```bash
cellphonedb plot dot_plot --means-path /path/to/means.txt --pvalues-path /path/to/pvalutes.txt
```
- for heatmap_plot
```bash
cellphonedb plot heatmap_plot /path/to/meta.txt --pvalues-path /path/to/pvalutes.txt
```

Alternatively, you can try to run the plotting scripts manually. You'll find them here: https://github.com/ventolab/CellphoneDB/tree/master/cellphonedb/src/plotters/R

**Comment by RuoyangShao** [comment]
Thanks a lot for the helpful reply @prete ,

As you reminded that Seurat was not required by CellPhoneDB at all, I realized I was running another Rstudio session at the same time. It looks like there may be conflicts when calling more than one R sessions. So I tried again after closing the other R session and it worked as expected. Hope this helps anyone, thanks again!
